#!/usr/bin/env python
from sys import argv
a="".join(a[:80]+" "*(80-len(a)) for a in open(argv[1]).read().split("\n")[:25])
a+=" "*(2000-len(a))
b=open("marsh","rb").read()
d=""
while 1:
	c=b.find((" "+d)*2000)
	if c!=-1:break
	d+="\0"
open(argv[2] if len(argv)==3 else argv[1]+".","wb").write(b[:c]+d.join(a)+d+b[c+(len(d)+1)*2000:])
