#!/usr/bin/env python
from sys import argv
a=[a[:80]+" "*(80-len(a)) for a in open(argv[1]).read().split("\n")[:25]]
a+=" "*(80*(25-len(a))),
b=open("marsh","rb").read()
c=b.find(" "*2000)
open(argv[2] if len(argv)==3 else argv[1]+".","wb").write(b[:c]+"".join(a)+b[c+2000:])
