[package]
name = "barfs"
version = "0.1.0"
authors = ["serprex"]
edition = "2018"

[dependencies]
cranelift = "0.78"
cranelift-codegen = "0.78"
cranelift-jit = "0.78"
cranelift-module = "0.78"
cranelift-native = "0.78"
fxhash = "0.2"
rand = "0.8"

