[package]
name = "barfs"
version = "0.1.1"
authors = ["serprex"]
edition = "2018"
license = "MIT"
description = "Befunge JIT"
repository = "https://github.com/serprex/Befunge/barfs"

[dependencies]
cranelift = "0.89"
cranelift-codegen = "0.89"
cranelift-jit = "0.89"
cranelift-module = "0.89"
cranelift-native = "0.89"
fxhash = "0.2"
rand = "0.8"

[profile.release]
panic = "abort"
lto = "thin"

